### ISSUE TITLE
autosave@1.0.0 is not intalling

### ISSUE THREAD

**Issue by cihadhoruzoglu** [NV/chrome-devtools-autosave-server#18]
I tried to update the new version, but it gives error. How can I install?

Screenshot: http://d1206.hizliresim.com/y/d/7td5c.jpg

**Comment by NV** [comment]
Fixed in e494244f54ba9fc3718b3e28ab517366020d7824. Please try to install again.

Thanks for reporting. I don’t test much on WIndows.

**Comment by cihadhoruzoglu** [comment]
I still getting the same error -_-

it says version still @1.0.0 not @1.0.1

**Comment by NV** [comment]
Could you run `npm install -g autosave` and copy/paste the result here?

**Comment by cihadhoruzoglu** [comment]
Result here: http://g1206.hizliresim.com/y/g/7wpg1.jpg

**Comment by NV** [comment]
That’s weird. You should try to uninstall it and then implicitly tell npm to install version 1.0.2:

```
npm uninstall -g autosave
npm install -g autosave@1.0.2
```

If it doesn’t help, you should ask a question on [npm mailing list](https://groups.google.com/forum/?fromgroups#!forum/npm-).

**Comment by cihadhoruzoglu** [comment]
I tried "npm uninstall -g autosave" first but it doesn't work.
Then i tried "npm install -g autosave@1.0.2" and works fine.

Thank you!

**Comment by dewwwey** [comment]
It looks like I have the same or at least a similar issue: [Screenshot](http://i.imgur.com/SQzh8.jpg)
Things I've tried so far:
- re-installing node.js
- re-installing the extension
- "npm uninstall -g autosave"
- "npm install -g autosave@1.0.2"
  Experimental APIs are on, I startet cmd with administrator rights.

**Comment by dewwwey** [comment]
It looks like I have the same or at least a similar issue: [Screenshot](http://i.imgur.com/SQzh8.jpg)
Things I've tried so far:
- re-installing node.js
- re-installing the extension
- "npm uninstall -g autosave"
- "npm install -g autosave@1.0.2"
  Experimental APIs are on, I startet cmd with administrator rights.
